name: Check Vercel Environment Configuration

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  contents: read

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  check-vercel-env:
    name: Check Vercel Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Check Vercel Authentication
        run: |
          echo "🔐 Checking Vercel authentication..."
          npx vercel whoami --token="${{ secrets.VERCEL_TOKEN }}"

      - name: List All Environment Variables
        run: |
          echo "📊 Listing all environment variables by environment..."
          echo ""

          echo "🏭 PRODUCTION Environment:"
          echo "========================="
          npx vercel env ls production --token="${{ secrets.VERCEL_TOKEN }}" || echo "No production variables found"
          echo ""

          echo "🔬 PREVIEW Environment:"
          echo "======================"
          npx vercel env ls preview --token="${{ secrets.VERCEL_TOKEN }}" || echo "No preview variables found"
          echo ""

          echo "🛠️ DEVELOPMENT Environment:"
          echo "=========================="
          npx vercel env ls development --token="${{ secrets.VERCEL_TOKEN }}" || echo "No development variables found"
          echo ""

      - name: Check Project Information
        run: |
          echo "📋 Project Information:"
          echo "====================="
          npx vercel project ls --token="${{ secrets.VERCEL_TOKEN }}"
          echo ""

          echo "🔧 Current Project Details:"
          echo "=========================="
          npx vercel inspect --token="${{ secrets.VERCEL_TOKEN }}" || echo "Could not inspect current project"

      - name: Analyze Current Configuration
        run: |
          echo "📁 Current Project Configuration:"
          echo "================================"

          echo "📄 vercel.json:"
          if [ -f vercel.json ]; then
            cat vercel.json
          else
            echo "No vercel.json found"
          fi
          echo ""

          echo "📁 .vercel directory:"
          if [ -d .vercel ]; then
            ls -la .vercel/
            if [ -f .vercel/project.json ]; then
              echo "Project config:"
              cat .vercel/project.json
            fi
          else
            echo "No .vercel directory found"
          fi

      - name: Check Required Environment Variables
        run: |
          echo "✅ Required Environment Variables Analysis:"
          echo "=========================================="

          echo ""
          echo "🎯 PRODUCTION should have:"
          echo "  VITE_SUPABASE_URL = https://gjftooyqkmijlvqbkwdr.supabase.co"
          echo "  VITE_SUPABASE_ANON_KEY = [Production Anon Key]"
          echo "  NODE_ENV = production"
          echo ""

          echo "🎯 PREVIEW should have:"
          echo "  VITE_SUPABASE_URL = https://slhyzoupwluxgasvapoc.supabase.co"
          echo "  VITE_SUPABASE_ANON_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          echo "  VITE_TEST_MODE = true"
          echo "  NODE_ENV = test"
          echo ""

          echo "📝 To add missing variables:"
          echo "  1. Go to https://vercel.com/dashboard"
          echo "  2. Select italian-flashcards project"
          echo "  3. Go to Settings → Environment Variables"
          echo "  4. Add each variable with proper environment assignment"

      - name: Summary
        run: |
          echo ""
          echo "🎉 Vercel Environment Check Complete!"
          echo "====================================="
          echo ""
          echo "✅ Check the output above to see your current environment variables"
          echo "📋 Compare with the required variables listed"
          echo "🔧 Use Vercel dashboard to add any missing variables"
          echo ""
          echo "🔗 Useful links:"
          echo "   - Vercel Dashboard: https://vercel.com/dashboard"
          echo "   - Test Database: https://app.supabase.com/project/slhyzoupwluxgasvapoc"
          echo "   - Production Database: https://app.supabase.com/project/gjftooyqkmijlvqbkwdr"